### ISSUE TITLE
Code review suggestions

### ISSUE THREAD

**Issue by lsorber** [Zac-HD/hypothesis-jsonschema#22]
Thanks for the nice package!

I have an implementation of a JSON schema strategy in Hypothesis [1], and was reviewing your implementation out of interest to see how you approached it.

We have a need for such a package, but I'd rather not maintain my own implementation. That's why I thought it might be useful to contribute some suggestions to help improve your implementation (I mean this in the most constructive way possible!). Here they are:

1. [`JSON_STRATEGY`](https://github.com/Zac-HD/hypothesis-jsonschema/blob/master/src/hypothesis_jsonschema/_impl.py#L25) is implemented using `defer`, but I think `recursive` might be a better fit here (see [`gen_document`](https://gist.github.com/lsorber/4d902733772fab270e6eb9f1c77a3690#file-hypothesis-jsonschema-py-L153)). Seems more idiomatic to me, and that way you have control over the depth of the recursion too.
2. The implementation of `object_schema` comments that you do black magic with private Hypothesis internals. I was able to implement the object strategy without having to resort to those techniques [4]. Although it admittedly does not implement `patternProperties`, I suspect you could use the same idea in your implementation to remove the black magic.
3. According to the JSON schema spec, a string `pattern` will match anywhere in the string [2]. If you want to match a full string, they recommend to write the `pattern` as `^...$`. Unfortunately, in Python `re.search('^abc$', 'abc\n')` finds a match (!), while `re.search('^abc$', 'abc\n\n')` does not. Meanwhile in JSON schema, neither of those two cases result in a match. Therefore, the `from_regex` strategy needs to be adapted to fix that edge case.
4. Looks like you haven't implemented the case that an array has `uniqueItems = true` and the items are a list.
5. Also, if an array's items are a dict, then the item's `type` property may be either a string or a list [3]. Looking at your implementation, it doesn't look like you handle the latter case.

[1] https://gist.github.com/lsorber/4d902733772fab270e6eb9f1c77a3690
[2] https://json-schema.org/understanding-json-schema/reference/string.html#regular-expressions
[3] https://gist.github.com/lsorber/4d902733772fab270e6eb9f1c77a3690#file-hypothesis-jsonschema-py-L84
[4] https://gist.github.com/lsorber/4d902733772fab270e6eb9f1c77a3690#file-hypothesis-jsonschema-py-L110

**Comment by lsorber** [comment]
Quick update with some light benchmarking:
- The current implementation in `hypothesis-jsonschema` takes about 138ms +- 17ms to generate a single instance of very simple `UserModel` schema (see below).
- With the improvements above, the time to generate a single instance of the same model is only 15.9ms +- 208µs.

UserModel schema:
```python
UserModel = {'title': 'UserModel',
 'type': 'object',
 'properties': {'name': {'title': 'Name', 'type': 'string'},
  'password1': {'title': 'Password1', 'type': 'string'},
  'password2': {'title': 'Password2', 'type': 'string'}},
 'required': ['name', 'password1', 'password2']}
```

**Comment by Zac-HD** [comment]
Hey @lsorber - thanks so much for your review!  I really appreciate the time and effort you've put in 😄 

I plan to investigate in more detail over the next few weeks as I have time, but some quick initial comments:

1. I'll benchmark `recursive()` and probably switch over!

2. The black magic in question gives `hypothesis-jsonschema` a much better chance of finding globally-minimal examples, rather than getting stuck in local minima.  I wouldn't recommend it to anyone but (a subset of) Hypothesis core developers, but it's useful to us 😉 

3. Unfortunately this comes down to differences between the JS and Python dialects of regular expressions - for example in Python [`$` matches the end of the string or just before the newline at the end of the string](https://docs.python.org/3/library/re.html#regular-expression-syntax).
   I've chosen to go with the Python syntax here, which matches the behaviour of the Python `jsonschema` library.  I also don't know of a library to use JS-regexes in Python, and it would be a *lot* of work to build a new `from_js_regex()` strategy.
   So in summary this is a known issue but I don't see a workable fix.

4. Good point!  I've opened an issue to add such schemas to the upstream test suite, and once that's done I'll pull them into this repo and ensure they're handled correctly.

5. [My `array_schema` function](https://github.com/Zac-HD/hypothesis-jsonschema/blob/359d42a0b5d6a7503e7305a207b454a55a9d49fa/src/hypothesis_jsonschema/_impl.py#L688-L713) doesn't do anything with the value of the `"items"` keyword beyond check whether it's a list or a dict (having already transformed the bool case), then pass it to `from_type`.  So I think it's fine?  If I've missed something please let me know!

Re: benchmarking, it would be great to see how you get those numbers!

In particular, if you're using `.example()` I would suggest instead running an `@given` test with `--hypothesis-show-statistics`.  My implementation here does a lot of work up-front to canonicalise, simplify, and merge schemas togther, and generally reshape things as much as possible for efficient generation and especially shrinking.  I've also focussed much more on worst-case than best-case timing, so while it may not be blazing fast it should also never be pathologically slow either.

And thanks again for your comments!

**Comment by lsorber** [comment]
Hi @Zac-HD, some quick responses:

1. Great :-).
2. Could you elaborate a bit on how you approach that?
3. I agree, but I do think it's worth it to address the `^...$` case because it is such a common case. It's also not expensive to do so (in lines of code and execution time). Would you consider that?
4. Nice, thanks!
5. I tested it and indeed it supports the case I described, so everything OK.

Here's a benchmark using the `@given` decorator you asked for:
```python
from hypothesis import given
from hypothesis_jsonschema import from_schema

user_model = {
    'title': 'UserModel',
    'type': 'object',
    'properties': {
        'name': {'title': 'Name', 'type': 'string'},
        'password1': {'title': 'Password1', 'type': 'string'},
        'password2': {'title': 'Password2', 'type': 'string'}
    },
    'required': ['name', 'password1', 'password2']
}

users = from_schema(user_model)  # hypothesis-json
users_2 = get_generator(user_model)  # gist

@given(users)
def test_user(user):
    ...

@given(users_2)
def test_user_2(user):
    ...

%timeit test_user()
%timeit test_user_2()
```
Benchmark results:
```
662 ms ± 91.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
108 ms ± 2.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Still a good amount of room for optimisations it seems (also note the variance). I was trying to see if I could get `hypothesis-jsonschema` working with `hypothesis-auto`, and unfortunately it's even slower there, to the point that it's probably too slow to use at this stage.

**Comment by Zac-HD** [comment]
Re (2), I'd suggest [our dev guide on shrinking](https://github.com/HypothesisWorks/hypothesis/blob/master/guides/strategies-that-shrink.rst); if you need more it's down to reading source code for examples and comments.  In particular the locality and collection-sizing is important in this case.

Re (3), `if pattern.startswith("^") and pattern.endswith("$"): <use fullmatch logic>` is pretty easy to code, and definitely worth doing.  Is there any other low-hanging fruit in regex syntax conversion?

Re: benchmarks... that does look like there should be some low-hanging performance fruit.  Unfortunately I think it's mostly that I need to significantly restructure the pre-processing to skip redundant work, but it's definitely on the vague todo list (as e.g. a precursor to production-ready reference resolution).  The rest of the difference I'd attribute to different handling of optional properties, I think, but will investigate later.

**Comment by lsorber** [comment]
(2) OK thanks for that reference, will be interesting to read up on.

(3) I've reviewed the differences between the JavaScript and Python regular expression engines [1], and besides addressing `$` newline problem, the other low hanging fruit I see is setting `re.ASCII` [2] because the character classes `\d` and `\w` only match ASCII characters in JavaScript.

[1] http://web.archive.org/web/20130830063653/http://www.regular-expressions.info:80/refflavors.html
[2] https://docs.python.org/3/library/re.html#re.ASCII

**Comment by Zac-HD** [comment]
(3) ... I think this is a larger issue again; the correct response is to add some upstream tests in the JSONSchema-test-suite, then write a function which compiles JS regex patterns in Python (IMO: as a new package), add that to the Python `jsonschema` library, and finally use it to compile the patterns here before handing off to `from_regex()`.  It'll be a project, but good for the ecosystem!

Re: `hypothesis-auto`, HypothesisWorks/hypothesis#2103 should explain - it's currently implemented in terms of `.example()`, which is not recommended for tests and will emit warnings under the latest version of Hypothesis accordingly.

Tactically: this has been a fantastic thread for discussion, but there's simply too much here to action.  I'm going to open a new issue for each specific suggestion, and then close this one... but please feel free to keep it going if you have more suggestions!

**Comment by lsorber** [comment]
Hey @Zac-HD, just coming back to a few of the above items quickly:
- I don't see an issue for replacing `deferred` with `recursive` -- would that be part of another issue? It might also be related to #24.
- I agree that the best response is #1, but I do think this package would benefit from a more short-term solution too. Addressing the `$` discrepancy would solve the most common difference. I've actually had hypothesis generate invalid (according to JSON schema) strings that were valid in Python in my tests, so it really does impact users directly!

**Comment by Zac-HD** [comment]
- I've already pushed a commit for that 😎
- I think we'll be fixing it properly here and upstream in `jsonschema` over the weekend, but if not I'll just patch the `$` difference.

**Comment by lsorber** [comment]
Great! Much appreciated.

**Comment by Zac-HD** [comment]
Julian/jsonschema#609
